version: "1.3"
services:
  server:
    build: ./
    container_name: diplomcloud
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/postgres
      spring.jpa.hibernate.ddl-auto: create-drop
    ports:
      - "8088:8088"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
